package com.common.base.model;

import com.jfinal.ext.annotation.TableColDesc;
import com.jfinal.ext.common.model.BaseModel;

/**
 * Generated by Timor, do not modify this file.false
 */
@SuppressWarnings("serial")
public class BaseGenConfigTemplate<M extends BaseModel<M>> extends BaseModel<M>{
	// 主键id
	@TableColDesc(name = "id", paraName = "id", label = "主键id", type = "text")
    public static final String ID = "id";
	// 配置id
	@TableColDesc(name = "config", paraName = "config", label = "配置id", type = "text")
    public static final String CONFIG = "config";
	// 名称
	@TableColDesc(name = "name", paraName = "name", label = "名称", type = "text")
    public static final String NAME = "name";
	// 类型
	@TableColDesc(name = "type", paraName = "type", label = "类型", type = "text")
    public static final String TYPE = "type";
	// 模板
	@TableColDesc(name = "template", paraName = "template", label = "模板", type = "text")
    public static final String TEMPLATE = "template";
	// 描述
	@TableColDesc(name = "description", paraName = "description", label = "描述", type = "text")
    public static final String DESCRIPTION = "description";
	// 状态 0 禁用 1 正常 
	@TableColDesc(name = "status", paraName = "status", label = "状态 0 禁用 1 正常 ", type = "text")
    public static final String STATUS = "status";





    // default generate getter and setter method.
    // - - - - - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - - - -

	// 主键id
	public void setId(String id) {
		set(ID, id);
	}

	// 主键id
	public String getId() {
		return getStr(ID);
	}

	// 配置id
	public void setConfig(String config) {
		set(CONFIG, config);
	}

	// 配置id
	public String getConfig() {
		return getStr(CONFIG);
	}

	// 名称
	public void setName(String name) {
		set(NAME, name);
	}

	// 名称
	public String getName() {
		return getStr(NAME);
	}

	// 类型
	public void setType(String type) {
		set(TYPE, type);
	}

	// 类型
	public String getType() {
		return getStr(TYPE);
	}

	// 模板
	public void setTemplate(String template) {
		set(TEMPLATE, template);
	}

	// 模板
	public String getTemplate() {
		return getStr(TEMPLATE);
	}

	// 描述
	public void setDescription(String description) {
		set(DESCRIPTION, description);
	}

	// 描述
	public String getDescription() {
		return getStr(DESCRIPTION);
	}

	// 状态 0 禁用 1 正常 
	public void setStatus(Integer status) {
		set(STATUS, status);
	}

	// 状态 0 禁用 1 正常 
	public Integer getStatus() {
		return getInt(STATUS);
	}

}
