package com.oillab.article.article.model;

import com.jfinal.ext.common.model.FindCondition;

import java.sql.Timestamp;

/**
 * Generated by Timor, do not modify this file.
 */
public class ArticleCondition extends FindCondition {
    private Integer id;
    private Integer mid;
    private String uid;
    private Integer views;
    private String title;
    private String type;
    private String typeName;
    private String author;
    private String description;
    private String coverImg;
    private String content;
    private Timestamp addTime;
    private Timestamp beginAddTime;
    private Timestamp endAddTime;
    private Timestamp pubTime;
    private Timestamp beginPubTime;
    private Timestamp endPubTime;
    private Timestamp lastEditTime;
    private Timestamp beginLastEditTime;
    private Timestamp endLastEditTime;
    private Integer status = 1;

    private String searchKey;

    @Override
    public String check() {
        return "";
    }

    // generator getter and setter method.
    // - - - - - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - - -


    public String getSearchKey() {
        return searchKey;
    }

    public void setSearchKey(String searchKey) {
        this.searchKey = searchKey;
    }

    public String getCoverImg() {
        return coverImg;
    }

    public void setCoverImg(String coverImg) {
        this.coverImg = coverImg;
    }

    public Timestamp getBeginAddTime() {
        return beginAddTime;
    }

    public void setBeginAddTime(Timestamp beginAddTime) {
        this.beginAddTime = beginAddTime;
    }

    public Timestamp getEndAddTime() {
        return endAddTime;
    }

    public void setEndAddTime(Timestamp endAddTime) {
        this.endAddTime = endAddTime;
    }

    public Timestamp getBeginPubTime() {
        return beginPubTime;
    }

    public void setBeginPubTime(Timestamp beginPubTime) {
        this.beginPubTime = beginPubTime;
    }

    public Timestamp getEndPubTime() {
        return endPubTime;
    }

    public void setEndPubTime(Timestamp endPubTime) {
        this.endPubTime = endPubTime;
    }

    public Timestamp getLastEditTime() {
        return lastEditTime;
    }

    public void setLastEditTime(Timestamp lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    public Timestamp getBeginLastEditTime() {
        return beginLastEditTime;
    }

    public void setBeginLastEditTime(Timestamp beginLastEditTime) {
        this.beginLastEditTime = beginLastEditTime;
    }

    public Timestamp getEndLastEditTime() {
        return endLastEditTime;
    }

    public void setEndLastEditTime(Timestamp endLastEditTime) {
        this.endLastEditTime = endLastEditTime;
    }

    // cid
    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    // cid
    @Override
    public Integer getId() {
        return this.id;
    }

    // 模块id
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    // 模块id
    public Integer getMid() {
        return this.mid;
    }

    // 发布文章管理员id
    public void setUid(String uid) {
        this.uid = uid;
    }

    // 发布文章管理员id
    public String getUid() {
        return this.uid;
    }

    // 浏览人数
    public void setViews(Integer views) {
        this.views = views;
    }

    // 浏览人数
    public Integer getViews() {
        return this.views;
    }

    // 标题
    public void setTitle(String title) {
        this.title = title;
    }

    // 标题
    public String getTitle() {
        return this.title;
    }

    // 文章类型
    public void setType(String type) {
        this.type = type;
    }

    // 文章类型
    public String getType() {
        return this.type;
    }

    // 文章作者
    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    // 文章作者
    public String getAuthor() {
        return this.author;
    }

    // 概要
    public void setDescription(String description) {
        this.description = description;
    }

    // 概要
    public String getDescription() {
        return this.description;
    }

    // 引导（封面）图片
    public void setCoverimg(String coverImg) {
        this.coverImg = coverImg;
    }

    // 引导（封面）图片
    public String getCoverimg() {
        return this.coverImg;
    }

    // 文章内容（富文本）
    public void setContent(String content) {
        this.content = content;
    }

    // 文章内容（富文本）
    public String getContent() {
        return this.content;
    }

    // 文章入库时间
    public void setAddTime(Timestamp addTime) {
        this.addTime = addTime;
    }

    // 文章入库时间
    public Timestamp getAddTime() {
        return this.addTime;
    }

    // 发布时间（自定义）
    public void setPubTime(Timestamp pubTime) {
        this.pubTime = pubTime;
    }

    // 发布时间（自定义）
    public Timestamp getPubTime() {
        return this.pubTime;
    }

    // 最后编辑时间
    public void setLasteditTime(Timestamp lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    // 最后编辑时间
    public Timestamp getLasteditTime() {
        return this.lastEditTime;
    }

    // 状态：禁用：-1；测试：0；启用：1；
    public void setStatus(Integer status) {
        this.status = status;
    }

    // 状态：禁用：-1；测试：0；启用：1；
    public Integer getStatus() {
        return this.status;
    }

}
