package com.common.base.model.generate;

import com.jfinal.ext.annotation.TableColDesc;
import com.jfinal.ext.common.model.BaseModel;

import java.util.Date;

/**
 * Generated by Timor, do not modify this file.false
 */
@SuppressWarnings("serial")
public class BaseFileConf<M extends BaseModel<M>> extends BaseModel<M>{
	// 自增主键idCOMMENT 
	@TableColDesc(name = "id", paraName = "id", label = "自增主键idCOMMENT ")
	public static final String ID = "id";
	@TableColDesc(name = "name", paraName = "name", label = "名称")
	public static final String NAME = "name";
	@TableColDesc(name = "title", paraName = "title", label = "标题")
	public static final String TITLE = "title";
	// 描述，如描述该业务类型对应的文件上传业务功能的业务表COMMENT
	@TableColDesc(name = "description", paraName = "description", label = "描述，如描述该业务类型对应的文件上传业务功能的业务表COMMENT ")
	public static final String DESCRIPTION = "description";
	// 允许上传的文件类型(mine-type标准)，为空时不限制类型COMMENT 
	@TableColDesc(name = "typeLimit", paraName = "typeLimit", label = "允许上传的文件类型(mine-type标准)，为空时不限制类型COMMENT ")
	public static final String TYPE_LIMIT = "typeLimit";
	@TableColDesc(name = "mineTypes", paraName = "mineTypes", label = "允许上传的文件类型(mine-type标准)，为空时不限制类型COMMENT ")
	public static final String MIME_TYPES = "mineTypes";
	// 允许上传的文件大小(kb)，为空时不限制大小COMMENT 
	@TableColDesc(name = "sizeLimit", paraName = "sizeLimit", label = "允许上传的文件大小(kb)，为空时不限制大小COMMENT ")
    public static final String SIZE_LIMIT = "sizeLimit";
	// 服务器存储文件的路径COMMENT 
	@TableColDesc(name = "uploadPath", paraName = "uploadPath", label = "服务器存储文件的路径COMMENT ")
	public static final String UPLOAD_PATH = "uploadPath";
	// 服务器存储文件的路径COMMENT
	@TableColDesc(name = "uploadUrl", paraName = "uploadUrl", label = "上传url")
	public static final String UPLOAD_URL = "uploadUrl";
	// 文件服务器存储绝对路径
	@TableColDesc(name = "absolutePath", paraName = "absolutePath", label = "文件服务器存储绝对路径相对basePath")
	public static final String ABSOLUTE_PATH = "absolutePath";
	// 文件相对路径，域名+此字段为该资源的请求地址
	@TableColDesc(name = "relativePath", paraName = "relativePath", label = "文件相对路径，域名+此字段为该资源的请求地址")
	public static final String RELATIVE_PATH = "relativePath";
	// 创建时间COMMENT 
	@TableColDesc(name = "creat_time", paraName = "creat_time", label = "创建时间COMMENT ")
    public static final String CREAT_TIME = "creat_time";
	// 最近修改时间COMMENT 
	@TableColDesc(name = "update_time", paraName = "update_time", label = "最近修改时间COMMENT ")
    public static final String UPDATE_TIME = "update_time";
	// 状态
	@TableColDesc(name = "status", paraName = "status", label = "状态")
	public static final String STATUS = "status";





    // default generate getter and setter method.
    // - - - - - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - - - -

	// 自增主键idCOMMENT 
	public void setId(String id) {
		set(ID, id);
	}

	// 自增主键idCOMMENT 
	@Override
	public String getId() {
		return getStr(ID);
	}

	public void setName(String name) {
		set(NAME, name);
	}

	public String getName() {
		return getStr(NAME);
	}

	public void setTitle(String title) {
		set(TITLE, title);
	}

	public String getTitle() {
		return getStr(TITLE);
	}

	// 描述，如描述该业务类型对应的文件上传业务功能的业务表COMMENT
	public void setDescription(String description) {
		set(DESCRIPTION, description);
	}

	// 描述，如描述该业务类型对应的文件上传业务功能的业务表COMMENT
	public String getDescription() {
		return getStr(DESCRIPTION);
	}

	// 允许上传的文件类型(后缀，不含.)，为空时不限制类型COMMENT
	public void setTypeLimit(String typeLimit) {
		set(TYPE_LIMIT, typeLimit);
	}

	// 允许上传的文件类型(后缀，不含.)，为空时不限制类型COMMENT
	public String getTypeLimit() {
		return getStr(TYPE_LIMIT);
	}

	// 允许上传的文件类型(mine-type标准)，为空时不限制类型COMMENT
	public void setMimeTypes(String mimeTypes) {
		set(MIME_TYPES, mimeTypes);
	}

	// 允许上传的文件类型(mine-type标准)，为空时不限制类型COMMENT
	public String getMimeTypes() {
		return getStr(MIME_TYPES);
	}

	// 允许上传的文件大小(kb)，为空时不限制大小COMMENT 
	public void setSizeLimit(Integer sizeLimit) {
		set(SIZE_LIMIT, sizeLimit);
	}

	// 允许上传的文件大小(kb)，为空时不限制大小COMMENT 
	public Integer getSizeLimit() {
		return getInt(SIZE_LIMIT);
	}

	// 服务器存储文件的路径COMMENT 
	public void setAbsolutePath(String path) {
		set(ABSOLUTE_PATH, path);
	}

	// 服务器存储文件的路径COMMENT 
	public String getAbsolutePath() {
		return getStr(ABSOLUTE_PATH);
	}

	// 外部访问文件资源相对根路径COMMENT
	public void setRelativePath(String relativePath) {
		set(RELATIVE_PATH, relativePath);
	}

	// 外部访问文件资源相对根路径COMMENT
	public String getRelativePath() {
		return getStr(RELATIVE_PATH);
	}

	public void setUploadPath(Integer uploadPath) {
		set(UPLOAD_PATH, uploadPath);
	}

	public Integer getUploadPath() {
		return getInt(UPLOAD_PATH);
	}

	public void setUploadUrl(Integer uploadUrl) {
		set(UPLOAD_URL, uploadUrl);
	}

	public Integer getUploadUrl() {
		return getInt(UPLOAD_URL);
	}

	// 创建时间COMMENT 
	public void setCreatTime(Date creatTime) {
		set(CREAT_TIME, creatTime);
	}

	// 创建时间COMMENT
	public Date getCreatTime() {
		return get(CREAT_TIME);
	}

	// 最近修改时间COMMENT
	public void setUpdateTime(Date updateTime) {
		set(UPDATE_TIME, updateTime);
	}

	// 最近修改时间COMMENT 
	public Date getUpdateTime() {
		return get(UPDATE_TIME);
	}

	public void setStatus(Integer status) {
		set(STATUS, status);
	}

	public Integer getStatus() {
		return getInt(STATUS);
	}
}
