package com.common.base.model.generate;

import com.jfinal.ext.annotation.TableColDesc;
import com.jfinal.ext.common.model.BaseModel;

/**
 * Generated by Timor, do not modify this file.false
 */
@SuppressWarnings("serial")
public class BaseFileInfo<M extends BaseModel<M>> extends BaseModel<M>{
	// 自增主键id
	@TableColDesc(name = "id", paraName = "id", label = "主键id")
    public static final String ID = "id";
	// 业务类型
	@TableColDesc(name = "businessType", paraName = "businessType", label = "业务类型")
    public static final String BUSINESS_TYPE = "businessType";
	// 业务id
	@TableColDesc(name = "config", paraName = "config", label = "文件上传配置")
    public static final String CONFIG = "config";
	// 文件原名称
	@TableColDesc(name = "originalName", paraName = "originalName", label = "文件原名称")
    public static final String ORIGINAL_NAME = "originalName";
	// 文件新名称(唯一)
	@TableColDesc(name = "newName", paraName = "newName", label = "文件新名称(唯一)")
    public static final String NEW_NAME = "newName";
	// 文件类型
	@TableColDesc(name = "type", paraName = "type", label = "文件类型")
    public static final String FILE_TYPE = "type";
	// 文件大小(kb)
	@TableColDesc(name = "size", paraName = "size", label = "文件大小(kb)")
    public static final String FILE_SIZE = "size";
	// 文件服务器存储绝对路径
	@TableColDesc(name = "absolutePath", paraName = "absolutePath", label = "文件服务器存储绝对路径")
    public static final String ABSOLUTE_PATH = "absolutePath";
	// 文件相对路径，域名+此字段为该资源的请求地址
	@TableColDesc(name = "relativePath", paraName = "relativePath", label = "文件相对路径，域名+此字段为该资源的请求地址")
    public static final String RELATIVE_PATH = "relativePath";
	// 创建时间
	@TableColDesc(name = "creatTime", paraName = "creatTime", label = "创建时间")
    public static final String CREAT_TIME = "creatTime";
	// 最近修改时间
	@TableColDesc(name = "updateTime", paraName = "updateTime", label = "最近修改时间")
    public static final String UPDATE_TIME = "updateTime";
	// 逻辑删除(默认0正常，1文件已被物理删除)
	@TableColDesc(name = "status", paraName = "status", label = "状态")
    public static final String STATUS = "status";
	private static final String HASH = "hash";
	private static final String URL = "url";


	// default generate getter and setter method.
    // - - - - - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - - - -

	// 自增主键id
	public void setId(String id) {
		set(ID, id);
	}

	// 自增主键id
	@Override
	public String getId() {
		return getStr(ID);
	}

	// 业务类型
	public void setBusinessType(String businessType) {
		set(BUSINESS_TYPE, businessType);
	}

	// 业务类型
	public String getBusinessType() {
		return getStr(BUSINESS_TYPE);
	}

	// 业务id
	public void setConfig(String configId) {
		set(CONFIG, configId);
	}

	// 业务id
	public String getConfig() {
		return getStr(CONFIG);
	}

	// 文件原名称
	public void setOriginalName(String originalName) {
		set(ORIGINAL_NAME, originalName);
	}

	// 文件原名称
	public String getOriginalName() {
		return getStr(ORIGINAL_NAME);
	}

	// 文件新名称(唯一)
	public void setNewName(String newName) {
		set(NEW_NAME, newName);
	}

	// 文件新名称(唯一)
	public String getNewName() {
		return getStr(NEW_NAME);
	}

	// 文件类型
	public void setFileType(String type) {
		set(FILE_TYPE, type);
	}

	// 文件类型
	public String getFileType() {
		return getStr(FILE_TYPE);
	}

	// 文件大小(kb)
	public void setFileSize(Integer fileSize) {
		set(FILE_SIZE, fileSize);
	}

	// 文件大小(kb)
	public Integer getFileSize() {
		return get(FILE_SIZE);
	}

	// 文件服务器存储绝对路径
	public void setAbsolutePath(String filePath) {
		set(ABSOLUTE_PATH, filePath);
	}

	// 文件服务器存储绝对路径
	public String getAbsolutePath() {
		return getStr(ABSOLUTE_PATH);
	}

	// 文件相对路径，域名+此字段为该资源的请求地址
	public void setRelativePath(String relativePath) {
		set(RELATIVE_PATH, relativePath);
	}

	// 文件相对路径，域名+此字段为该资源的请求地址
	public String getRelativePath() {
		return getStr(RELATIVE_PATH);
	}

	// 创建时间
	public void setCreatTime(java.util.Date creatTime) {
		set(CREAT_TIME, creatTime);
	}

	// 创建时间
	public java.util.Date getCreatTime() {
		return get(CREAT_TIME);
	}

	// 最近修改时间
	public void setUpdateTime(java.util.Date lastUpdateTime) {
		set(UPDATE_TIME, lastUpdateTime);
	}

	// 最近修改时间
	public java.util.Date getUpdateTime() {
		return get(UPDATE_TIME);
	}

	public void setStatus(Integer status) {
		set(STATUS, status);
	}

	public Integer getStatus() {
		return getInt(STATUS);
	}


	public void setResourceUrl(String url) {
		set(URL, url);
	}

	public String getResourceUrl() {
		return get(URL);
	}


	public void setHash(String hash) {
		set(HASH, hash);
	}

	public String getHash() {
		return get(HASH);
	}

}
