package com.common.base.model.generate;

import com.jfinal.ext.common.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends BaseModel<M> implements IBean {
	// cid
	public void setId(Integer id) {
		set("id", id);
	}

	// cid
	public Integer getId() {
		return getInt("id");
	}

	// 模块id
	public void setMid(Integer mid) {
		set("mid", mid);
	}

	// 模块id
	public Integer getMid() {
		return getInt("mid");
	}

	// 发布文章管理员id
	public void setUid(String uid) {
		set("uid", uid);
	}

	// 发布文章管理员id
	public String getUid() {
		return getStr("uid");
	}

	// 浏览人数
	public void setViews(Integer views) {
		set("views", views);
	}

	// 浏览人数
	public Integer getViews() {
		return getInt("views");
	}

	// 标题
	public void setTitle(String title) {
		set("title", title);
	}

	// 标题
	public String getTitle() {
		return getStr("title");
	}

	// 文章类型
	public void setType(String type) {
		set("type", type);
	}

	// 文章类型
	public String getType() {
		return getStr("type");
	}

	// 文章类型
	public void setTypeName(String typeName) {
		set("typeName", typeName);
	}

	// 文章类型
	public String getTypeName() {
		return getStr("typeName");
	}

	// 文章作者
	public void setAuthor(String author) {
		set("author", author);
	}

	// 文章作者
	public String getAuthor() {
		return getStr("author");
	}

	// 概要
	public void setDescription(String description) {
		set("description", description);
	}

	// 概要
	public String getDescription() {
		return getStr("description");
	}

	// 引导（封面）图片
	public void setCoverImg(String coverImg) {
		set("coverImg", coverImg);
	}

	// 引导（封面）图片
	public String getCoverImg() {
		return getStr("coverImg");
	}

	// 文章内容（富文本）
	public void setContent(String content) {
		set("content", content);
	}

	// 文章内容（富文本）
	public String getContent() {
		return getStr("content");
	}

	// 文章入库时间
	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}

	// 文章入库时间
	public java.util.Date getAddTime() {
		return get("addTime");
	}

	// 发布时间（自定义）
	public void setPubTime(java.util.Date pubTime) {
		set("pubTime", pubTime);
	}

	// 发布时间（自定义）
	public java.util.Date getPubTime() {
		return get("pubTime");
	}

	// 最后编辑时间
	public void setLastEditTime(java.util.Date lastEditTime) {
		set("lastEditTime", lastEditTime);
	}

	// 最后编辑时间
	public java.util.Date getLastEditTime() {
		return get("lastEditTime");
	}

	// 状态：禁用：-1；测试：0；启用：1；
	public void setStatus(Integer status) {
		set("status", status);
	}

	// 状态：禁用：-1；测试：0；启用：1；
	public Integer getStatus() {
		return getInt("status");
	}

}
