package com.common.base.model.generate;

import com.jfinal.ext.common.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysDictType<M extends BaseSysDictType<M>> extends BaseModel<M> implements IBean {
	// 字典类型id
	public void setId(String id) {
		set("id", id);
	}

	// 字典类型id
	public String getId() {
		return getStr("id");
	}

	// 字典类型名
	public void setName(String name) {
		set("name", name);
	}

	// 字典类型名
	public String getName() {
		return getStr("name");
	}

	// 类型
	public void setType(String type) {
		set("typeName", type);
	}

	// 类型
	public String getType() {
		return getStr("typeName");
	}

	// 描述
	public void setDescription(String description) {
		set("description", description);
	}

	// 描述
	public String getDescription() {
		return getStr("description");
	}

	// 状态
	public void setStatus(Integer status) {
		set("status", status);
	}

	// 状态
	public Integer getStatus() {
		return getInt("status");
	}

}
