package com.common.base.model.generate;

import com.jfinal.ext.common.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTemplate<M extends BaseTemplate<M>> extends BaseModel<M> implements IBean {

	/**
	 * id
	 */
	public void setId(Integer id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	@Override
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 模板名称
	 */
	public void setName(String name) {
		set("name", name);
	}
	
	/**
	 * 模板名称
	 */
	public String getName() {
		return getStr("name");
	}

	/**
	 * 类型
	 */
	public void setType(String type) {
		set("type", type);
	}

	/**
	 * 类型
	 */
	public String getType() {
		return getStr("type");
	}

	/**
	 * 模板内容
	 */
	public void setTemplate(String template) {
		set("template", template);
	}

	/**
	 * 模板内容
	 */
	public String getTemplate() {
		return getStr("template");
	}

	/**
	 * 备注
	 */
	public void setRemark(String remark) {
		set("remark", remark);
	}

	/**
	 * 备注
	 */
	public String getRemark() {
		return getStr("remark");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 最后编辑时间
	 */
	public void setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
	}

	/**
	 * 最后编辑时间
	 */
	public java.util.Date getEditTime() {
		return get("edit_time");
	}

	/**
	 * 状态：禁用：-1；测试：0；启用：1；
	 */
	public void setStatus(Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态：禁用：-1；测试：0；启用：1；
	 */
	public Integer getStatus() {
		return getInt("status");
	}

}
