package com.common.base.model.generate;

import com.jfinal.ext.common.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductType<M extends BaseProductType<M>> extends BaseModel<M> implements IBean {
	// 产品类型id
	public void setId(String id) {
		set("id", id);
	}

	// 产品类型id
	@Override
	public String getId() {
		return getStr("id");
	}

	// 产品类型名
	public void setName(String name) {
		set("name", name);
	}

	// 产品类型名
	public String getName() {
		return getStr("name");
	}

	// 产品种类id
	public void setCategory(String category) {
		set("category", category);
	}

	// 产品种类id
	public String getCategory() {
		return getStr("category");
	}

	// 类型描述
	public void setDescription(String description) {
		set("description", description);
	}

	// 类型描述
	public String getDescription() {
		return getStr("description");
	}

	// 状态（0：不展示；1：展示）
	public void setStatus(Integer status) {
		set("status", status);
	}

	// 状态（0：不展示；1：展示）
	public Integer getStatus() {
		return getInt("status");
	}

}
