package com.common.base.model.generate;

import com.jfinal.ext.common.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends BaseModel<M> implements IBean {
	// 产品id
	public void setId(String id) {
		set("id", id);
	}

	// 产品id
	@Override
	public String getId() {
		return getStr("id");
	}

	// 产品名称
	public void setName(String name) {
		set("name", name);
	}

	// 产品名称
	public String getName() {
		return getStr("name");
	}

	// 产品种类（大类，比如XXX实验仪器）
	public void setCategory(String category) {
		set("category", category);
	}

	// 产品种类（大类，比如XXX实验仪器）
	public String getCategory() {
		return getStr("category");
	}

	// 产品类型（小类，比如XXX实验仪）
	public void setType(String type) {
		set("type", type);
	}

	// 产品类型（小类，比如XXX实验仪）
	public String getType() {
		return getStr("type");
	}

	// 产品型号（产品具体型号）
	public void setModel(String model) {
		set("model", model);
	}

	// 产品型号（产品具体型号）
	public String getModel() {
		return getStr("model");
	}

	// 这是产品展示图片
	public void setCoverImg(String coverImg) {
		set("coverImg", coverImg);
	}

	// 这是产品展示图片
	public String getCoverImg() {
		return getStr("coverImg");
	}

	// 产品描述（简要）
	public void setDescription(String description) {
		set("description", description);
	}

	// 产品描述（简要）
	public String getDescription() {
		return getStr("description");
	}

	// 产品介绍（详细）
	public void setIntroduction(String introduction) {
		set("introduction", introduction);
	}

	// 产品介绍（详细）
	public String getIntroduction() {
		return getStr("introduction");
	}

	// 产品资料（提供给客户下载参考）
	public void setResource(String resource) {
		set("resource", resource);
	}

	// 产品资料（提供给客户下载参考）
	public String getResource() {
		return getStr("resource");
	}

	// 产品状态
	public void setStatus(Integer status) {
		set("status", status);
	}

	// 产品状态
	public Integer getStatus() {
		return getInt("status");
	}

}
