package com.common.base.model.generate;

import com.jfinal.ext.common.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarousel<M extends BaseCarousel<M>> extends BaseModel<M> implements IBean {
	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	// 类型:0:PC，1:H5，2:APP
	public void setType(Integer type) {
		set("type", type);
	}

	// 类型:0:PC，1:H5，2:APP
	public Integer getType() {
		return getInt("type");
	}

	// 轮播图名字: 区别不同的轮播图
	public void setName(String name) {
		set("name", name);
	}

	// 轮播图名字: 区别不同的轮播图
	public String getName() {
		return getStr("name");
	}

	// 链接地址
	public void setUrl(String url) {
		set("url", url);
	}

	// 链接地址
	public String getUrl() {
		return getStr("url");
	}

	// 封面图片
	public void setCoverImg(String coverImg) {
		set("coverImg", coverImg);
	}

	// 封面图片
	public String getCoverImg() {
		return getStr("coverImg");
	}

	// 轮播图停留时间
	public void setInterval(Integer interval) {
		set("interval", interval);
	}

	// 轮播图停留时间
	public Integer getInterval() {
		return getInt("interval");
	}

	// 图片描述interval
	public void setDescription(String description) {
		set("description", description);
	}

	// 图片描述
	public String getDescription() {
		return getStr("description");
	}

	// 备注信息
	public void setRemark(String remark) {
		set("remark", remark);
	}

	// 备注信息
	public String getRemark() {
		return getStr("remark");
	}

	// 排序
	public void setSort(Integer sort) {
		set("sort", sort);
	}

	// 排序
	public Integer getSort() {
		return get("sort");
	}

	// 创建时间
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	// 创建时间
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	// 修改时间
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	// 修改时间
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	// 操作人ID
	public void setOperatorId(String operatorId) {
		set("operatorId", operatorId);
	}

	// 操作人ID
	public String getOperatorId() {
		return getStr("operatorId");
	}

	// 状态 0 禁用 1 正常 
	public void setStatus(Integer status) {
		set("status", status);
	}

	// 状态 0 禁用 1 正常 
	public Integer getStatus() {
		return get("status");
	}

}
