package com.common.base.model.generate;

import com.jfinal.ext.common.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModularType<M extends BaseModularType<M>> extends BaseModel<M> implements IBean {
	// 主键id
	public void setId(Integer id) {
		set("id", id);
	}

	// 主键id
	@Override
	public Integer getId() {
		return getInt("id");
	}

	// 类型名称
	public void setName(String name) {
		set("name", name);
	}

	// 类型名称
	public String getName() {
		return getStr("name");
	}

	// 类型名称
	public void setTitle(String title) {
		set("title", title);
	}

	// 类型名称
	public String getTitle() {
		return getStr("title");
	}

	// 类型描述
	public void setDescription(String description) {
		set("description", description);
	}

	// 类型描述
	public String getDescription() {
		return getStr("description");
	}

	// 状态
	public void setStatus(Integer status) {
		set("status", status);
	}

	// 状态
	public Integer getStatus() {
		return getInt("status");
	}

}
