package com.common.base.model.generate;

import com.jfinal.ext.common.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysConfig<M extends BaseSysConfig<M>> extends BaseModel<M> implements IBean {
	// 配置id
	public void setId(String id) {
		set("id", id);
	}

	// 配置id
	public String getId() {
		return getStr("id");
	}

	// 配置项
	public void setName(String name) {
		set("name", name);
	}

	// 配置项
	public String getName() {
		return getStr("name");
	}

	// 值
	public void setValue(String value) {
		set("value", value);
	}

	// 值
	public String getValue() {
		return getStr("value");
	}

	// 描述
	public void setDescription(String description) {
		set("description", description);
	}

	// 描述
	public String getDescription() {
		return getStr("description");
	}

	// 类型是否可改变（0：可变；1：不可变）
	public void setFixed(Integer fixed) {
		set("fixed", fixed);
	}

	// 类型是否可改变（0：可变；1：不可变）
	public Integer getFixed() {
		return getInt("fixed");
	}

}
