package xyz.xpman.system.dict.model;

import com.common.base.model.generate.BaseSysDict;
import com.jfinal.ext.annotation.TableBind;
import com.jfinal.ext.annotation.TableColDesc;
import com.jfinal.ext.annotation.TableDesc;
import com.jfinal.ext.util.rand.MyUUIDUtil;
import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "sys_dict", primaryKey = "id")
@TableDesc(label = "字典", width = "100%", height = "675px")
public class Dict extends BaseSysDict<Dict> {
    @TableColDesc(name = "id", paraName = "id", label = "id", type = "number")
    public static final String ID = "id";
    @TableColDesc(name = "name", paraName = "name", label = "name", type = "text")
    public static final String NAME = "name";
    @TableColDesc(name = "type", paraName = "type", label = "类型", type = "text")
    public static final String TYPE = "type";
    @TableColDesc(name = "typeName", paraName = "typeName", label = "类型名", type = "text")
    public static final String TYPE_NAME = "typeName";
    @TableColDesc(name = "value", paraName = "value", label = "值", type = "text")
    public static final String VALUE = "value";
    @TableColDesc(name = "description", paraName = "description", label = "描述", type = "text")
    public static final String DESCRIPTION = "description";
    @TableColDesc(name = "sort", paraName = "sort", label = "排序", type = "number")
    public static final String SORT = "sort";
    @TableColDesc(name = "fixed", paraName = "fixed", label = "值是否可变", type = "number")
    public static final String STATUS = "fixed";

    @Override
    public String checkCommonFiled() {
        // check
        if(StrKit.isBlank(getName())){
            return "字典名不能为空!";
        }
        if(StrKit.isBlank(getType())){
            return "字典类型不能为空!";
        }
        if(StrKit.isBlank(getValue())){
            return "字典值不能为空!";
        }

        // set default value
        if(null == getFixed()){
            setFixed(0);
        }
        if(null == getSort()){
            setSort(1);
        }
        return EMPTY_STRING;
    }

    @Override
    public String checkForAdd() {
        return checkForAdd(()->{
            this.setId(MyUUIDUtil.getUUID());
            return EMPTY_STRING;
        });
    }


}
