# jfinal config
common:
  devMode: true
  packing: true
  template:
    inClassPath: true
  viewPath:
  # other config
  baseUploadPath: /home/root/oillab/webapp/upload
  baseDownloadPath: /home/root/oillab/webapp/upload
  baseTemplatePath: webapp

  # 扫描jar包设置
  scanJars: baseModel-1.0.jar|common-1.0.jar|business-1.0.jar|web-1.0.jar
  scanPackages:


# db config
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:6033/oillab?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: oillab
  password: 'ayf782yt87!'

  # dbcp config
druid:
  monitor: /admin/druid/monitor/1122

