package com.oillab.modular.modular.model;

import com.common.base.model.generate.BaseModular;
import com.jfinal.ext.annotation.TableBind;
import com.jfinal.ext.annotation.TableColDesc;
import com.jfinal.ext.annotation.TableDesc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "modular", primaryKey = "id")
@TableDesc(label = "栏目", width = "100%", height = "675px")
public class Modular extends BaseModular<Modular> {
    @TableColDesc(name = "id", paraName = "id", label = "id", type = "number")
    public static final String ID = "id";
    @TableColDesc(name = "name", paraName = "name", label = "name")
    public static final String NAME = "name";
//    @TableColDesc(name = "type", paraName = "type", label = "类型")
    public static final String TYPE = "type";
    @TableColDesc(name = "typeTitle", paraName = "typeTitle", label = "类型")
    public static final String TYPE_NAME = "typeTitle";
    @TableColDesc(name = "title", paraName = "title", label = "标题")
    public static final String TITLE = "title";
    @TableColDesc(name = "englishTitle", paraName = "englishTitle", label = "英文标题")
    public static final String ENGLISH_TITLE = "englishTitle";
    @TableColDesc(name = "url", paraName = "url", label = "链接", format = "urlFmt")
    public static final String URL = "url";
    @TableColDesc(name = "config", paraName = "config", label = "配置文件", format = "urlFmt")
    public static final String CONFIG = "config";
    @TableColDesc(name = "status", paraName = "status", label = "状态", type = "number", format = "statusFmt")
    public static final String STATUS = "status";

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    public String getTypeTitle() {
        return getStr("typeTitle");
    }

    public void setTypeTitle(String typeTitle) {
        set("typeTitle", typeTitle);
    }

}
