package com.oillab.template.model;

import com.common.base.model.generate.BaseTemplate;
import com.jfinal.ext.annotation.TableBind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@TableBind(tableName = "html_template", primaryKey = "id")
public class Template extends BaseTemplate<Template> {

}
